### ISSUE TITLE
Style changes, Fonts and sizes

### ISSUE THREAD

**Issue by dtiradob** [freeolabini/freeolabini.github.io#208]
I would like to propose the change of some fonts, to Avenir in the titles and keep the serif one on text. Also some changes in sizes for titles and text:
![2019-05-24-161842_1242x1208_scrot](https://user-images.githubusercontent.com/1088534/58334438-da2e0800-7e3f-11e9-8cc6-a858252f38fe.png)

**Comment by iliasbartolini** [comment]
I'm also feeling the lack of a good common style guide across the web and other media.
 
FYI. For the flyers and stickers I was switching to Oswald - mostly because it is similar to what other flyers have been using. https://fonts.google.com/specimen/Oswald
Probably does not fit well in the website but wanted to share for context.

I'm not an expert in this field so I will leave others the decision.
I like the new version you're proposing more for the web.

**Comment by dtiradob** [comment]
@iliasbartolini thanks!, I'm also not an expert, I was following some recommendations (from UX people) to use the serif for text and non serif for titles. I chose Avenir as is one of that comes with tachyons. http://tachyons.io/docs/typography/font-family/ 
I like Oswald and is good to use for stickers and graphics, for the web I prefer something more standard so people can focus on the content.

**Comment by claucece** [comment]
Hey

@iliasbartolini yeah.. oswald seems nice. Maybe we can use the oswald for the titles and the avenir for the text (or open sans)?

**Comment by claucece** [comment]
What about this one? This is with open sans light sans serif
<img width="1207" alt="Screen Shot 2019-05-26 at 10 18 46 AM" src="https://user-images.githubusercontent.com/8270508/58379113-b681d380-7f9f-11e9-9c8d-6729cd1d1e20.png">

**Comment by dtiradob** [comment]
@claucece I like the sans serif for text too. do you want that specific one?

**Comment by claucece** [comment]
@dtiradob check the commit ;) I can increase the font-weight if needed

**Comment by pedropalau** [comment]
I've made a lot of UI (colors, fonts, styles) improvements. This issue is ready to be closed.
